[environments.development]
user = "SA"
password = "${localSecret.Flyway Desktop 1ce21ebd-d7fb-4b54-a34b-d627335360c7}"

[environments.shadow]
user = "SA"
password = "${localSecret.Flyway Desktop 1ce21ebd-d7fb-4b54-a34b-d627335360c7}"

[environments.Prod]
user = "SA"
password = "${localSecret.Flyway Desktop 1ce21ebd-d7fb-4b54-a34b-d627335360c7}"

[environments.Test]
user = "SA"
password = "${localSecret.Flyway Desktop 1ce21ebd-d7fb-4b54-a34b-d627335360c7}"

[environments.Check]
user = "SA"
password = "${localSecret.Flyway Desktop 1ce21ebd-d7fb-4b54-a34b-d627335360c7}"

[environments.Build]
user = "SA"
password = "${localSecret.Flyway Desktop 1ce21ebd-d7fb-4b54-a34b-d627335360c7}"