SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Creating [Customers].[CustomerAccounts]'
GO
CREATE TABLE [Customers].[CustomerAccounts]
(
[col1] [int] NULL,
[col2] [int] NULL,
[col3] [int] NULL
)
GO

